create table if not exists public.agentech_accounts (
  email text primary key,
  password_hash text not null,
  salt text not null,
  created_at timestamptz not null default now(),
  verified_at timestamptz not null default now()
);

create table if not exists public.agentech_verification_codes (
  email text primary key,
  code text not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create table if not exists public.agentech_counters (
  key text primary key,
  value integer not null default 0,
  updated_at timestamptz not null default now()
);

insert into public.agentech_counters (key, value)
values ('children_enrolled', 0)
on conflict (key) do nothing;

create table if not exists public.agentech_profiles (
  email text primary key references public.agentech_accounts(email) on delete cascade,
  first_name text not null default '',
  last_name text not null default '',
  phone text not null default '',
  company text,
  address text,
  dob date,
  account_type text check (account_type in ('individual', 'group')),
  department text,
  discount_percent numeric(5,2),
  updated_at timestamptz not null default now()
);

alter table public.agentech_profiles add column if not exists department text;
alter table public.agentech_profiles add column if not exists discount_percent numeric(5,2);

create table if not exists public.agentech_children (
  id bigint generated by default as identity primary key,
  parent_email text not null references public.agentech_accounts(email) on delete cascade,
  first_name text not null,
  last_name text not null,
  dob date not null,
  grade text not null,
  sex text not null,
  school_info text,
  preferred_location text,
  created_at timestamptz not null default now()
);

alter table public.agentech_children add column if not exists school_info text;
alter table public.agentech_children add column if not exists preferred_location text;
alter table public.agentech_children add column if not exists selected_course_code text;
alter table public.agentech_children add column if not exists selected_course_title text;

create or replace function public.agentech_title_case_name(value text)
returns text
language sql
immutable
as $$
  select coalesce(nullif(initcap(lower(trim(value))), ''), '');
$$;

create or replace function public.agentech_normalize_profile_names()
returns trigger
language plpgsql
as $$
begin
  new.first_name = public.agentech_title_case_name(new.first_name);
  new.last_name = public.agentech_title_case_name(new.last_name);
  return new;
end;
$$;

create or replace function public.agentech_normalize_child_names()
returns trigger
language plpgsql
as $$
begin
  new.first_name = public.agentech_title_case_name(new.first_name);
  new.last_name = public.agentech_title_case_name(new.last_name);
  return new;
end;
$$;

drop trigger if exists agentech_profiles_normalize_names on public.agentech_profiles;
create trigger agentech_profiles_normalize_names
before insert or update of first_name, last_name
on public.agentech_profiles
for each row
execute function public.agentech_normalize_profile_names();

drop trigger if exists agentech_children_normalize_names on public.agentech_children;
create trigger agentech_children_normalize_names
before insert or update of first_name, last_name
on public.agentech_children
for each row
execute function public.agentech_normalize_child_names();

update public.agentech_profiles
set
  first_name = public.agentech_title_case_name(first_name),
  last_name = public.agentech_title_case_name(last_name);

update public.agentech_children
set
  first_name = public.agentech_title_case_name(first_name),
  last_name = public.agentech_title_case_name(last_name);

create table if not exists public.agentech_sites (
  site_name text primary key,
  info text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.agentech_classes (
  class_id text primary key,
  site_name text references public.agentech_sites(site_name) on delete set null,
  class_name text not null,
  class_time text not null,
  starting_date date not null,
  age_range text not null,
  price numeric(10,2) not null,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.agentech_course_locations (
  location_code text primary key,
  city text not null,
  state text,
  location_name text not null,
  address text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.agentech_education_courses (
  course_code text primary key,
  location_code text references public.agentech_course_locations(location_code) on delete set null,
  grade_slug text not null,
  course_name text not null,
  course_title text not null,
  course_description text,
  flyer_image text,
  preview_description text,
  class_time text not null,
  starting_date date,
  age_range text not null,
  price numeric(10,2) not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.agentech_course_locations (location_code, city, state, location_name, address)
values ('WALNUT', 'Walnut', 'CA', 'Walnut', null)
on conflict (location_code) do update
set
  city = excluded.city,
  state = excluded.state,
  location_name = excluded.location_name,
  address = excluded.address,
  updated_at = now();

insert into public.agentech_education_courses (
  course_code,
  location_code,
  grade_slug,
  course_name,
  course_title,
  course_description,
  flyer_image,
  preview_description,
  class_time,
  starting_date,
  age_range,
  price,
  active
)
values (
  'W001',
  'WALNUT',
  'k-2',
  'AI Imagination Summer Camp K-2',
  'Walnut 2026 Summer K-2',
  'AI Imagination Summer Camp for Grades K-2 in Walnut.',
  '/assets/class advertisements/Flyers/k-2 eng.png',
  'Walnut 2026 summer K-2',
  '2026 Summer',
  '2026-06-01',
  'Grades K-2',
  499,
  true
)
on conflict (course_code) do update
set
  location_code = excluded.location_code,
  grade_slug = excluded.grade_slug,
  course_name = excluded.course_name,
  course_title = excluded.course_title,
  course_description = excluded.course_description,
  flyer_image = excluded.flyer_image,
  preview_description = excluded.preview_description,
  class_time = excluded.class_time,
  starting_date = excluded.starting_date,
  age_range = excluded.age_range,
  price = excluded.price,
  active = excluded.active,
  updated_at = now();

insert into public.agentech_education_courses (
  course_code,
  location_code,
  grade_slug,
  course_name,
  course_title,
  course_description,
  flyer_image,
  preview_description,
  class_time,
  starting_date,
  age_range,
  price,
  active
)
values
(
  'W002',
  'WALNUT',
  '3-5',
  'AI Imagination Summer Camp 3-5',
  'Walnut 2026 Summer Grades 3-5',
  'AI Imagination Summer Camp for Grades 3-5 in Walnut.',
  '/assets/class advertisements/Flyers/3-5.png',
  'Walnut 2026 Summer Grades 3-5',
  '2026 Summer',
  '2026-06-01',
  'Grades 3-5',
  499,
  true
),
(
  'W003',
  'WALNUT',
  '6-8',
  'AI Creation Camp 6-8',
  'Walnut 2026 Summer Grades 6-8',
  'AI Creation Camp for Grades 6-8 in Walnut.',
  '/assets/class advertisements/Flyers/6-8.png',
  'Walnut 2026 Summer Grades 6-8',
  '2026 Summer',
  '2026-06-01',
  'Grades 6-8',
  699,
  true
)
on conflict (course_code) do update
set
  location_code = excluded.location_code,
  grade_slug = excluded.grade_slug,
  course_name = excluded.course_name,
  course_title = excluded.course_title,
  course_description = excluded.course_description,
  flyer_image = excluded.flyer_image,
  preview_description = excluded.preview_description,
  class_time = excluded.class_time,
  starting_date = excluded.starting_date,
  age_range = excluded.age_range,
  price = excluded.price,
  active = excluded.active,
  updated_at = now();

create table if not exists public.agentech_enrollments (
  id bigint generated by default as identity primary key,
  parent_email text not null references public.agentech_accounts(email) on delete cascade,
  child_id bigint not null references public.agentech_children(id) on delete cascade,
  site_name text references public.agentech_sites(site_name) on delete set null,
  class_id text references public.agentech_classes(class_id) on delete set null,
  price numeric(10,2),
  paid boolean not null default false,
  invoice_email_sent_at timestamptz,
  created_at timestamptz not null default now(),
  unique(parent_email, child_id, class_id)
);

alter table public.agentech_enrollments add column if not exists invoice_email_sent_at timestamptz;

create table if not exists public.agentech_preorder_invoices (
  id bigint generated by default as identity primary key,
  invoice_number text not null unique,
  product text not null,
  email text not null,
  name text not null,
  phone text not null,
  company text,
  notes text,
  status text not null default 'invoice_email_pending',
  online_payment_accepted boolean not null default false,
  total_amount numeric(10,2),
  created_at timestamptz not null default now()
);

alter table public.agentech_preorder_invoices add column if not exists total_amount numeric(10,2);

create table if not exists public.agentech_invoice_items (
  id bigint generated by default as identity primary key,
  email text not null,
  source_type text not null check (source_type in ('robot', 'course', 'other')),
  source_id text,
  item_name text not null,
  child_id bigint references public.agentech_children(id) on delete set null,
  class_id text references public.agentech_classes(class_id) on delete set null,
  quantity integer not null default 1,
  unit_price numeric(10,2) not null,
  amount numeric(10,2) not null,
  paid boolean not null default false,
  invoice_email_sent_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists agentech_invoice_items_email_paid_idx
on public.agentech_invoice_items (email, paid, created_at);

create table if not exists public.agentech_workshop_applications (
  id bigint generated by default as identity primary key,
  account_email text not null references public.agentech_accounts(email) on delete cascade,
  name text not null,
  email text not null,
  school text not null,
  grade text not null,
  gpa text not null,
  interests text[] not null default '{}',
  experience text not null,
  parent_email text not null,
  resume_filename text,
  resume_storage_path text,
  notes text,
  status text not null default 'submitted',
  created_at timestamptz not null default now()
);

alter table public.agentech_workshop_applications add column if not exists resume_filename text;
alter table public.agentech_workshop_applications add column if not exists resume_storage_path text;

create index if not exists agentech_workshop_applications_account_idx
on public.agentech_workshop_applications (account_email, created_at desc);

create table if not exists public.agentech_ai_robotics_club_applications (
  id bigint generated by default as identity primary key,
  account_email text not null references public.agentech_accounts(email) on delete cascade,
  name text not null,
  email text not null,
  school text not null,
  grade text not null,
  gpa text not null,
  interests text[] not null default '{}',
  experience text not null,
  parent_email text not null,
  projects text not null,
  uniqueness text not null,
  resume_filename text,
  resume_storage_path text,
  notes text,
  status text not null default 'submitted',
  created_at timestamptz not null default now()
);

alter table public.agentech_ai_robotics_club_applications add column if not exists resume_filename text;
alter table public.agentech_ai_robotics_club_applications add column if not exists resume_storage_path text;

create index if not exists agentech_ai_robotics_club_applications_account_idx
on public.agentech_ai_robotics_club_applications (account_email, created_at desc);

create table if not exists public.agentech_internship_applications (
  id bigint generated by default as identity primary key,
  account_email text not null references public.agentech_accounts(email) on delete cascade,
  name text not null,
  email text not null,
  organization text not null,
  major text not null,
  graduation_year text not null,
  location text not null,
  role_interests text[] not null default '{}',
  profile_link text,
  built text not null,
  why_agentech text not null,
  resume_filename text not null,
  resume_storage_path text not null,
  notes text,
  status text not null default 'submitted',
  created_at timestamptz not null default now()
);

create index if not exists agentech_internship_applications_account_idx
on public.agentech_internship_applications (account_email, created_at desc);

alter table public.agentech_accounts enable row level security;
alter table public.agentech_verification_codes enable row level security;
alter table public.agentech_counters enable row level security;
alter table public.agentech_profiles enable row level security;
alter table public.agentech_children enable row level security;
alter table public.agentech_sites enable row level security;
alter table public.agentech_classes enable row level security;
alter table public.agentech_course_locations enable row level security;
alter table public.agentech_education_courses enable row level security;
alter table public.agentech_enrollments enable row level security;
alter table public.agentech_preorder_invoices enable row level security;
alter table public.agentech_invoice_items enable row level security;
alter table public.agentech_workshop_applications enable row level security;
alter table public.agentech_ai_robotics_club_applications enable row level security;
alter table public.agentech_internship_applications enable row level security;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('talent-resumes', 'talent-resumes', false, 5242880, array['application/pdf'])
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;
