create table if not exists public.agentech_accounts (
  email text primary key,
  password_hash text not null,
  salt text not null,
  first_name text not null default '',
  last_name text not null default '',
  phone text not null default '',
  credit_balance integer not null default 0 check (credit_balance >= 0),
  paid_credit_balance integer not null default 0 check (paid_credit_balance >= 0),
  bonus_credit_balance integer not null default 0 check (bonus_credit_balance >= 0),
  developer_latest_code_submission_id text,
  developer_physical_safety_status text,
  developer_physical_safety_passed_at timestamptz,
  developer_ai_security_status text,
  developer_ai_security_passed_at timestamptz,
  created_at timestamptz not null default now(),
  verified_at timestamptz not null default now()
);

alter table public.agentech_accounts add column if not exists first_name text not null default '';
alter table public.agentech_accounts add column if not exists last_name text not null default '';
alter table public.agentech_accounts add column if not exists phone text not null default '';
alter table public.agentech_accounts add column if not exists credit_balance integer not null default 0;
alter table public.agentech_accounts add column if not exists paid_credit_balance integer not null default 0;
alter table public.agentech_accounts add column if not exists bonus_credit_balance integer not null default 0;
alter table public.agentech_accounts add column if not exists developer_latest_code_submission_id text;
alter table public.agentech_accounts add column if not exists developer_physical_safety_status text;
alter table public.agentech_accounts add column if not exists developer_physical_safety_passed_at timestamptz;
alter table public.agentech_accounts add column if not exists developer_ai_security_status text;
alter table public.agentech_accounts add column if not exists developer_ai_security_passed_at timestamptz;

update public.agentech_accounts
set paid_credit_balance = credit_balance
where paid_credit_balance = 0
  and bonus_credit_balance = 0
  and credit_balance > 0;

create table if not exists public.agentech_account_profiles (
  id bigint generated by default as identity primary key,
  account_email text not null references public.agentech_accounts(email) on delete cascade,
  profile_type text not null check (profile_type in ('developer', 'student', 'teacher', 'talent')),
  username text not null unique,
  display_name text not null default '',
  first_name text,
  last_name text,
  dob date,
  grade text,
  sex text,
  school_info text,
  preferred_location text,
  credit_limit integer not null default 0 check (credit_limit >= 0),
  credits_used integer not null default 0 check (credits_used >= 0),
  monthly_credit_limit integer not null default 0 check (monthly_credit_limit >= 0),
  monthly_credits_used integer not null default 0 check (monthly_credits_used >= 0),
  monthly_usage_period text not null default to_char(now(), 'YYYY-MM'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.agentech_account_profiles add column if not exists username text;
alter table public.agentech_account_profiles add column if not exists first_name text;
alter table public.agentech_account_profiles add column if not exists last_name text;
alter table public.agentech_account_profiles add column if not exists dob date;
alter table public.agentech_account_profiles add column if not exists grade text;
alter table public.agentech_account_profiles add column if not exists sex text;
alter table public.agentech_account_profiles add column if not exists school_info text;
alter table public.agentech_account_profiles add column if not exists preferred_location text;
update public.agentech_account_profiles
set username = concat(profile_type, '-', id::text)
where username is null or username = '';
alter table public.agentech_account_profiles alter column username set not null;
alter table public.agentech_account_profiles add column if not exists monthly_credit_limit integer not null default 0;
alter table public.agentech_account_profiles add column if not exists monthly_credits_used integer not null default 0;
alter table public.agentech_account_profiles add column if not exists monthly_usage_period text not null default to_char(now(), 'YYYY-MM');
update public.agentech_account_profiles
set monthly_credit_limit = credit_limit
where monthly_credit_limit = 0
  and credit_limit > 0;

create index if not exists agentech_account_profiles_account_idx
on public.agentech_account_profiles (account_email, created_at desc);

create unique index if not exists agentech_account_profiles_username_idx
on public.agentech_account_profiles (username);

create table if not exists public.agentech_verification_codes (
  email text primary key,
  code text not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create table if not exists public.agentech_counters (
  key text primary key,
  value integer not null default 0,
  updated_at timestamptz not null default now()
);

insert into public.agentech_counters (key, value)
values ('children_enrolled', 0)
on conflict (key) do nothing;

create table if not exists public.agentech_profiles (
  email text primary key references public.agentech_accounts(email) on delete cascade,
  first_name text not null default '',
  last_name text not null default '',
  phone text not null default '',
  company text,
  address text,
  dob date,
  account_type text check (account_type in ('individual', 'group')),
  department text,
  discount_percent numeric(5,2),
  updated_at timestamptz not null default now()
);

alter table public.agentech_profiles add column if not exists department text;
alter table public.agentech_profiles add column if not exists discount_percent numeric(5,2);

create table if not exists public.agentech_children (
  id bigint generated by default as identity primary key,
  parent_email text not null references public.agentech_accounts(email) on delete cascade,
  first_name text not null,
  last_name text not null,
  dob date not null,
  grade text not null,
  sex text not null,
  school_info text,
  preferred_location text,
  created_at timestamptz not null default now()
);

alter table public.agentech_children add column if not exists school_info text;
alter table public.agentech_children add column if not exists preferred_location text;
alter table public.agentech_children add column if not exists selected_course_code text;
alter table public.agentech_children add column if not exists selected_course_title text;

create or replace function public.agentech_title_case_name(value text)
returns text
language sql
immutable
as $$
  select coalesce(nullif(initcap(lower(trim(value))), ''), '');
$$;

create or replace function public.agentech_normalize_profile_names()
returns trigger
language plpgsql
as $$
begin
  new.first_name = public.agentech_title_case_name(new.first_name);
  new.last_name = public.agentech_title_case_name(new.last_name);
  return new;
end;
$$;

create or replace function public.agentech_normalize_child_names()
returns trigger
language plpgsql
as $$
begin
  new.first_name = public.agentech_title_case_name(new.first_name);
  new.last_name = public.agentech_title_case_name(new.last_name);
  return new;
end;
$$;

drop trigger if exists agentech_profiles_normalize_names on public.agentech_profiles;
create trigger agentech_profiles_normalize_names
before insert or update of first_name, last_name
on public.agentech_profiles
for each row
execute function public.agentech_normalize_profile_names();

drop trigger if exists agentech_children_normalize_names on public.agentech_children;
create trigger agentech_children_normalize_names
before insert or update of first_name, last_name
on public.agentech_children
for each row
execute function public.agentech_normalize_child_names();

update public.agentech_profiles
set
  first_name = public.agentech_title_case_name(first_name),
  last_name = public.agentech_title_case_name(last_name);

update public.agentech_children
set
  first_name = public.agentech_title_case_name(first_name),
  last_name = public.agentech_title_case_name(last_name);

create table if not exists public.agentech_sites (
  site_name text primary key,
  info text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.agentech_classes (
  class_id text primary key,
  site_name text references public.agentech_sites(site_name) on delete set null,
  class_name text not null,
  class_time text not null,
  starting_date date not null,
  age_range text not null,
  price numeric(10,2) not null,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.agentech_course_locations (
  location_code text primary key,
  city text not null,
  state text,
  location_name text not null,
  address text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.agentech_education_courses (
  course_code text primary key,
  location_code text references public.agentech_course_locations(location_code) on delete set null,
  grade_slug text not null,
  course_name text not null,
  course_title text not null,
  course_description text,
  flyer_image text,
  preview_description text,
  class_time text not null,
  starting_date date,
  age_range text not null,
  price numeric(10,2) not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.agentech_course_locations (location_code, city, state, location_name, address)
values ('WALNUT', 'Walnut', 'CA', 'Walnut', null)
on conflict (location_code) do update
set
  city = excluded.city,
  state = excluded.state,
  location_name = excluded.location_name,
  address = excluded.address,
  updated_at = now();

insert into public.agentech_education_courses (
  course_code,
  location_code,
  grade_slug,
  course_name,
  course_title,
  course_description,
  flyer_image,
  preview_description,
  class_time,
  starting_date,
  age_range,
  price,
  active
)
values (
  'W001',
  'WALNUT',
  'k-2',
  'AI Imagination Summer Camp K-2',
  'Walnut 2026 Summer K-2',
  'AI Imagination Summer Camp for Grades K-2 in Walnut.',
  '/assets/class advertisements/Flyers/k-2 eng.png',
  'Walnut 2026 summer K-2',
  '2026 Summer',
  '2026-06-01',
  'Grades K-2',
  499,
  true
)
on conflict (course_code) do update
set
  location_code = excluded.location_code,
  grade_slug = excluded.grade_slug,
  course_name = excluded.course_name,
  course_title = excluded.course_title,
  course_description = excluded.course_description,
  flyer_image = excluded.flyer_image,
  preview_description = excluded.preview_description,
  class_time = excluded.class_time,
  starting_date = excluded.starting_date,
  age_range = excluded.age_range,
  price = excluded.price,
  active = excluded.active,
  updated_at = now();

insert into public.agentech_education_courses (
  course_code,
  location_code,
  grade_slug,
  course_name,
  course_title,
  course_description,
  flyer_image,
  preview_description,
  class_time,
  starting_date,
  age_range,
  price,
  active
)
values
(
  'W002',
  'WALNUT',
  '3-5',
  'AI Imagination Summer Camp 3-5',
  'Walnut 2026 Summer Grades 3-5',
  'AI Imagination Summer Camp for Grades 3-5 in Walnut.',
  '/assets/class advertisements/Flyers/3-5.png',
  'Walnut 2026 Summer Grades 3-5',
  '2026 Summer',
  '2026-06-01',
  'Grades 3-5',
  499,
  true
),
(
  'W003',
  'WALNUT',
  '6-8',
  'AI Creation Camp 6-8',
  'Walnut 2026 Summer Grades 6-8',
  'AI Creation Camp for Grades 6-8 in Walnut.',
  '/assets/class advertisements/Flyers/6-8.png',
  'Walnut 2026 Summer Grades 6-8',
  '2026 Summer',
  '2026-06-01',
  'Grades 6-8',
  699,
  true
)
on conflict (course_code) do update
set
  location_code = excluded.location_code,
  grade_slug = excluded.grade_slug,
  course_name = excluded.course_name,
  course_title = excluded.course_title,
  course_description = excluded.course_description,
  flyer_image = excluded.flyer_image,
  preview_description = excluded.preview_description,
  class_time = excluded.class_time,
  starting_date = excluded.starting_date,
  age_range = excluded.age_range,
  price = excluded.price,
  active = excluded.active,
  updated_at = now();

create table if not exists public.agentech_enrollments (
  id bigint generated by default as identity primary key,
  parent_email text not null references public.agentech_accounts(email) on delete cascade,
  child_id bigint not null references public.agentech_children(id) on delete cascade,
  site_name text references public.agentech_sites(site_name) on delete set null,
  class_id text references public.agentech_classes(class_id) on delete set null,
  price numeric(10,2),
  paid boolean not null default false,
  invoice_email_sent_at timestamptz,
  created_at timestamptz not null default now(),
  unique(parent_email, child_id, class_id)
);

alter table public.agentech_enrollments add column if not exists invoice_email_sent_at timestamptz;

create table if not exists public.agentech_preorder_invoices (
  id bigint generated by default as identity primary key,
  invoice_number text not null unique,
  product text not null,
  email text not null,
  name text not null,
  phone text not null,
  company text,
  notes text,
  status text not null default 'invoice_email_pending',
  online_payment_accepted boolean not null default false,
  total_amount numeric(10,2),
  created_at timestamptz not null default now()
);

alter table public.agentech_preorder_invoices add column if not exists total_amount numeric(10,2);

create table if not exists public.agentech_invoice_items (
  id bigint generated by default as identity primary key,
  email text not null,
  source_type text not null check (source_type in ('robot', 'course', 'other')),
  source_id text,
  item_name text not null,
  child_id bigint references public.agentech_children(id) on delete set null,
  class_id text references public.agentech_classes(class_id) on delete set null,
  quantity integer not null default 1,
  unit_price numeric(10,2) not null,
  amount numeric(10,2) not null,
  paid boolean not null default false,
  invoice_email_sent_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists agentech_invoice_items_email_paid_idx
on public.agentech_invoice_items (email, paid, created_at);

create table if not exists public.agentech_billing_invoices (
  id bigint generated by default as identity primary key,
  invoice_number text not null unique,
  email text not null,
  customer_name text,
  customer_phone text,
  customer_company text,
  customer_address text,
  status text not null default 'sent',
  currency text not null default 'usd',
  subtotal numeric(10,2) not null default 0,
  tax_rate numeric(6,3) not null default 0,
  tax_amount numeric(10,2) not null default 0,
  discount_amount numeric(10,2) not null default 0,
  total_amount numeric(10,2) not null default 0,
  amount_paid numeric(10,2) not null default 0,
  notes text,
  terms text,
  stripe_checkout_session_id text,
  stripe_payment_intent_id text,
  due_date date,
  sent_at timestamptz,
  paid_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.agentech_billing_invoices add column if not exists customer_phone text;
alter table public.agentech_billing_invoices add column if not exists customer_company text;
alter table public.agentech_billing_invoices add column if not exists customer_address text;
alter table public.agentech_billing_invoices add column if not exists stripe_checkout_session_id text;
alter table public.agentech_billing_invoices add column if not exists stripe_payment_intent_id text;
alter table public.agentech_billing_invoices add column if not exists due_date date;
alter table public.agentech_billing_invoices add column if not exists sent_at timestamptz;
alter table public.agentech_billing_invoices add column if not exists paid_at timestamptz;
alter table public.agentech_billing_invoices add column if not exists updated_at timestamptz not null default now();

create index if not exists agentech_billing_invoices_email_created_idx
on public.agentech_billing_invoices (email, created_at desc);

create index if not exists agentech_billing_invoices_status_created_idx
on public.agentech_billing_invoices (status, created_at desc);

create table if not exists public.agentech_billing_invoice_lines (
  id bigint generated by default as identity primary key,
  invoice_number text not null references public.agentech_billing_invoices(invoice_number) on delete cascade,
  source_item_id bigint,
  source_type text not null default 'other',
  source_id text,
  description text not null,
  quantity integer not null default 1,
  unit_price numeric(10,2) not null default 0,
  amount numeric(10,2) not null default 0,
  child_id bigint references public.agentech_children(id) on delete set null,
  class_id text references public.agentech_classes(class_id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists agentech_billing_invoice_lines_invoice_idx
on public.agentech_billing_invoice_lines (invoice_number, id);

create table if not exists public.agentech_account_credit_payments (
  id bigint generated by default as identity primary key,
  email text not null,
  credits integer not null check (credits > 0),
  amount_cents integer not null check (amount_cents > 0),
  currency text not null default 'usd',
  status text not null default 'pending' check (status in ('pending', 'paid', 'failed', 'refunded')),
  stripe_checkout_session_id text unique,
  stripe_payment_intent_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists agentech_account_credit_payments_email_created_idx
on public.agentech_account_credit_payments (email, created_at desc);

create table if not exists public.agentech_code_submissions (
  id text primary key,
  email text not null references public.agentech_accounts(email) on delete cascade,
  developer_name text not null,
  robot_model text not null,
  run_mode text not null,
  source text not null default 'pasted_code' check (source in ('pasted_code', 'uploaded_file', 'github')),
  uploaded_file_name text,
  github_repo_url text,
  github_branch text,
  commands text[] not null default '{}',
  code text not null default '',
  physical_safety_status text not null default 'pending' check (physical_safety_status in ('pending', 'passed', 'failed')),
  ai_security_status text not null default 'locked' check (ai_security_status in ('locked', 'pending', 'passed', 'failed', 'error')),
  ai_security_model text,
  ai_security_summary text,
  ai_security_findings jsonb not null default '[]'::jsonb,
  ai_security_risk_level text,
  ai_security_reviewed_at timestamptz,
  credits_charged integer not null default 0 check (credits_charged >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists agentech_code_submissions_email_created_idx
on public.agentech_code_submissions (email, created_at desc);

create index if not exists agentech_code_submissions_gate_idx
on public.agentech_code_submissions (email, physical_safety_status, ai_security_status);

alter table public.agentech_code_submissions add column if not exists uploaded_file_name text;
alter table public.agentech_code_submissions drop constraint if exists agentech_code_submissions_source_check;
alter table public.agentech_code_submissions add constraint agentech_code_submissions_source_check
check (source in ('pasted_code', 'uploaded_file', 'github'));

create table if not exists public.agentech_robot_sessions (
  id bigint generated by default as identity primary key,
  email text not null,
  access_profile_id bigint references public.agentech_account_profiles(id) on delete set null,
  profile_username text,
  profile_type text check (profile_type in ('developer', 'student', 'teacher', 'talent')),
  session_title text not null,
  robot_model text,
  scheduled_start timestamptz,
  scheduled_end timestamptz,
  session_status text not null default 'requested',
  requested_run_type text not null default 'preset_demo' check (requested_run_type in ('preset_demo', 'custom_code')),
  approved_run_type text not null default 'preset_demo' check (approved_run_type in ('preset_demo', 'custom_code')),
  preset_demo text,
  benchmark_status text not null default 'not_started' check (benchmark_status in ('not_started', 'pending', 'passed', 'failed')),
  price numeric(10,2) not null default 0,
  invoice_number text references public.agentech_billing_invoices(invoice_number) on delete set null,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.agentech_robot_sessions add column if not exists access_profile_id bigint references public.agentech_account_profiles(id) on delete set null;
alter table public.agentech_robot_sessions add column if not exists profile_username text;
alter table public.agentech_robot_sessions add column if not exists profile_type text;
alter table public.agentech_robot_sessions add column if not exists requested_run_type text not null default 'preset_demo';
alter table public.agentech_robot_sessions add column if not exists approved_run_type text not null default 'preset_demo';
alter table public.agentech_robot_sessions add column if not exists preset_demo text;
alter table public.agentech_robot_sessions add column if not exists benchmark_status text not null default 'not_started';

create index if not exists agentech_robot_sessions_email_created_idx
on public.agentech_robot_sessions (email, created_at desc);

create index if not exists agentech_robot_sessions_profile_scheduled_idx
on public.agentech_robot_sessions (access_profile_id, scheduled_start desc);

create table if not exists public.agentech_admin_users (
  email text primary key,
  role text not null default 'admin',
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.agentech_workshop_applications (
  id bigint generated by default as identity primary key,
  account_email text not null references public.agentech_accounts(email) on delete cascade,
  name text not null,
  email text not null,
  school text not null,
  grade text not null,
  gpa text not null,
  interests text[] not null default '{}',
  experience text not null,
  parent_email text not null,
  resume_filename text,
  resume_storage_path text,
  notes text,
  status text not null default 'submitted',
  created_at timestamptz not null default now()
);

alter table public.agentech_workshop_applications add column if not exists resume_filename text;
alter table public.agentech_workshop_applications add column if not exists resume_storage_path text;

create index if not exists agentech_workshop_applications_account_idx
on public.agentech_workshop_applications (account_email, created_at desc);

create table if not exists public.agentech_ai_robotics_club_applications (
  id bigint generated by default as identity primary key,
  account_email text not null references public.agentech_accounts(email) on delete cascade,
  name text not null,
  email text not null,
  school text not null,
  grade text not null,
  gpa text not null,
  interests text[] not null default '{}',
  experience text not null,
  parent_email text not null,
  projects text not null,
  uniqueness text not null,
  resume_filename text,
  resume_storage_path text,
  notes text,
  status text not null default 'submitted',
  created_at timestamptz not null default now()
);

alter table public.agentech_ai_robotics_club_applications add column if not exists resume_filename text;
alter table public.agentech_ai_robotics_club_applications add column if not exists resume_storage_path text;

create index if not exists agentech_ai_robotics_club_applications_account_idx
on public.agentech_ai_robotics_club_applications (account_email, created_at desc);

create table if not exists public.agentech_internship_applications (
  id bigint generated by default as identity primary key,
  account_email text not null references public.agentech_accounts(email) on delete cascade,
  name text not null,
  email text not null,
  organization text not null,
  major text not null,
  graduation_year text not null,
  location text not null,
  role_interests text[] not null default '{}',
  profile_link text,
  built text not null,
  why_agentech text not null,
  resume_filename text not null,
  resume_storage_path text not null,
  notes text,
  status text not null default 'submitted',
  created_at timestamptz not null default now()
);

create index if not exists agentech_internship_applications_account_idx
on public.agentech_internship_applications (account_email, created_at desc);

create table if not exists public.agentech_field_interest_leads (
  id bigint generated by default as identity primary key,
  email text not null,
  interest_area text not null,
  notes text,
  source text not null default 'field_qr',
  status text not null default 'new',
  created_at timestamptz not null default now()
);

create index if not exists agentech_field_interest_leads_created_idx
on public.agentech_field_interest_leads (created_at desc);

alter table public.agentech_accounts enable row level security;
alter table public.agentech_verification_codes enable row level security;
alter table public.agentech_counters enable row level security;
alter table public.agentech_profiles enable row level security;
alter table public.agentech_children enable row level security;
alter table public.agentech_sites enable row level security;
alter table public.agentech_classes enable row level security;
alter table public.agentech_course_locations enable row level security;
alter table public.agentech_education_courses enable row level security;
alter table public.agentech_enrollments enable row level security;
alter table public.agentech_preorder_invoices enable row level security;
alter table public.agentech_invoice_items enable row level security;
alter table public.agentech_billing_invoices enable row level security;
alter table public.agentech_billing_invoice_lines enable row level security;
alter table public.agentech_account_credit_payments enable row level security;
alter table public.agentech_code_submissions enable row level security;
alter table public.agentech_robot_sessions enable row level security;
alter table public.agentech_admin_users enable row level security;
alter table public.agentech_workshop_applications enable row level security;
alter table public.agentech_ai_robotics_club_applications enable row level security;
alter table public.agentech_internship_applications enable row level security;
alter table public.agentech_field_interest_leads enable row level security;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('talent-resumes', 'talent-resumes', false, 5242880, array['application/pdf'])
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;
