create table if not exists public.agentech_accounts (
  email text primary key,
  password_hash text not null,
  salt text not null,
  created_at timestamptz not null default now(),
  verified_at timestamptz not null default now()
);

create table if not exists public.agentech_verification_codes (
  email text primary key,
  code text not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create table if not exists public.agentech_counters (
  key text primary key,
  value integer not null default 0,
  updated_at timestamptz not null default now()
);

insert into public.agentech_counters (key, value)
values ('children_enrolled', 0)
on conflict (key) do nothing;

create table if not exists public.agentech_profiles (
  email text primary key references public.agentech_accounts(email) on delete cascade,
  first_name text not null default '',
  last_name text not null default '',
  phone text not null default '',
  company text,
  address text,
  dob date,
  account_type text check (account_type in ('individual', 'group')),
  department text,
  discount_percent numeric(5,2),
  updated_at timestamptz not null default now()
);

alter table public.agentech_profiles add column if not exists department text;
alter table public.agentech_profiles add column if not exists discount_percent numeric(5,2);

create table if not exists public.agentech_children (
  id bigint generated by default as identity primary key,
  parent_email text not null references public.agentech_accounts(email) on delete cascade,
  first_name text not null,
  last_name text not null,
  dob date not null,
  grade text not null,
  sex text not null,
  school_info text,
  preferred_location text,
  created_at timestamptz not null default now()
);

alter table public.agentech_children add column if not exists school_info text;
alter table public.agentech_children add column if not exists preferred_location text;

create table if not exists public.agentech_sites (
  site_name text primary key,
  info text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.agentech_classes (
  class_id text primary key,
  site_name text references public.agentech_sites(site_name) on delete set null,
  class_name text not null,
  class_time text not null,
  starting_date date not null,
  age_range text not null,
  price numeric(10,2) not null,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.agentech_enrollments (
  id bigint generated by default as identity primary key,
  parent_email text not null references public.agentech_accounts(email) on delete cascade,
  child_id bigint not null references public.agentech_children(id) on delete cascade,
  site_name text references public.agentech_sites(site_name) on delete set null,
  class_id text references public.agentech_classes(class_id) on delete set null,
  price numeric(10,2),
  paid boolean not null default false,
  invoice_email_sent_at timestamptz,
  created_at timestamptz not null default now(),
  unique(parent_email, child_id, class_id)
);

alter table public.agentech_enrollments add column if not exists invoice_email_sent_at timestamptz;

create table if not exists public.agentech_preorder_invoices (
  id bigint generated by default as identity primary key,
  invoice_number text not null unique,
  product text not null,
  email text not null,
  name text not null,
  phone text not null,
  company text,
  notes text,
  status text not null default 'invoice_email_pending',
  online_payment_accepted boolean not null default false,
  total_amount numeric(10,2),
  created_at timestamptz not null default now()
);

alter table public.agentech_preorder_invoices add column if not exists total_amount numeric(10,2);

create table if not exists public.agentech_invoice_items (
  id bigint generated by default as identity primary key,
  email text not null,
  source_type text not null check (source_type in ('robot', 'course', 'other')),
  source_id text,
  item_name text not null,
  child_id bigint references public.agentech_children(id) on delete set null,
  class_id text references public.agentech_classes(class_id) on delete set null,
  quantity integer not null default 1,
  unit_price numeric(10,2) not null,
  amount numeric(10,2) not null,
  paid boolean not null default false,
  invoice_email_sent_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists agentech_invoice_items_email_paid_idx
on public.agentech_invoice_items (email, paid, created_at);

create table if not exists public.agentech_workshop_applications (
  id bigint generated by default as identity primary key,
  account_email text not null references public.agentech_accounts(email) on delete cascade,
  name text not null,
  email text not null,
  school text not null,
  grade text not null,
  gpa text not null,
  interests text[] not null default '{}',
  experience text not null,
  parent_email text not null,
  notes text,
  status text not null default 'submitted',
  created_at timestamptz not null default now()
);

create index if not exists agentech_workshop_applications_account_idx
on public.agentech_workshop_applications (account_email, created_at desc);

create table if not exists public.agentech_ai_robotics_club_applications (
  id bigint generated by default as identity primary key,
  account_email text not null references public.agentech_accounts(email) on delete cascade,
  name text not null,
  email text not null,
  school text not null,
  grade text not null,
  gpa text not null,
  interests text[] not null default '{}',
  experience text not null,
  parent_email text not null,
  projects text not null,
  uniqueness text not null,
  notes text,
  status text not null default 'submitted',
  created_at timestamptz not null default now()
);

create index if not exists agentech_ai_robotics_club_applications_account_idx
on public.agentech_ai_robotics_club_applications (account_email, created_at desc);

create table if not exists public.agentech_internship_applications (
  id bigint generated by default as identity primary key,
  account_email text not null references public.agentech_accounts(email) on delete cascade,
  name text not null,
  email text not null,
  organization text not null,
  major text not null,
  graduation_year text not null,
  location text not null,
  role_interests text[] not null default '{}',
  profile_link text,
  built text not null,
  why_agentech text not null,
  resume_filename text not null,
  resume_storage_path text not null,
  notes text,
  status text not null default 'submitted',
  created_at timestamptz not null default now()
);

create index if not exists agentech_internship_applications_account_idx
on public.agentech_internship_applications (account_email, created_at desc);

alter table public.agentech_accounts enable row level security;
alter table public.agentech_verification_codes enable row level security;
alter table public.agentech_counters enable row level security;
alter table public.agentech_profiles enable row level security;
alter table public.agentech_children enable row level security;
alter table public.agentech_sites enable row level security;
alter table public.agentech_classes enable row level security;
alter table public.agentech_enrollments enable row level security;
alter table public.agentech_preorder_invoices enable row level security;
alter table public.agentech_invoice_items enable row level security;
alter table public.agentech_workshop_applications enable row level security;
alter table public.agentech_ai_robotics_club_applications enable row level security;
alter table public.agentech_internship_applications enable row level security;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('talent-resumes', 'talent-resumes', false, 5242880, array['application/pdf'])
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;
